version: "3.7"
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=omeka-s
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306"

  omeka:
    build: omeka_docker
    volumes:
      - files:/var/www/html/files
    depends_on:
      - db
      #- solr
    ports:
      - "8001:80"

  ocr-service:
    build: ocr_service
    restart: always
    depends_on:
      - omeka
    env_file:
     - env_variables


  # solr:
  #   image: solr:8.8.2
  #   volumes:
  #     - solr-data:/var/solr
  #   ports:
  #     - "8983:8983"


volumes:
  db-data:
  files:
  # solr-data:
