version: "3.7"
services:
  db:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=omeka-s
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    expose:
      - "3306"
    ports:
      - "3306:3306"

  backend:
    image: biblibre/omeka-s:3.0.2
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - OMEKA_ADMIN_EMAIL=seg.benoit@gmail.com
      - OMEKA_ADMIN_NAME=Benoit
      - OMEKA_ADMIN_PASSWORD=r365Yl1fN&M
    volumes:
      - ./omeka-modules:/var/www/html/modules
        # - backend-config:/var/www/providence/app/conf
        # - backend-media:/var/www/providence/media/
    depends_on:
      - db
      - solr
    ports:
      - "80:80"

  solr:
    image: solr:8.8.2
    volumes:
      - solr-data:/var/solr
    expose:
      - "8983"
    ports:
      - "8983:8983"

volumes:
  db-data:
  solr-data:
