version: "3.7"
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=omeka-s
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306"

  omeka:
    build: omeka_docker
    volumes:
      - files:/var/www/html/files
    depends_on:
      - db
      #- solr
    ports:
      - "8001:80"

  ocr-service:
    build: ocr_service
    depends_on:
      - omeka
    environment:
      - KEY_IDENTITY=QA8IzqSOYXKsFyz3qXJa2qC4WFHb7G5e
      - KEY_CREDENTIAL=a28JA5cETnfAWXu8siCawJoPk5sHy30Q


  # solr:
  #   image: solr:8.8.2
  #   volumes:
  #     - solr_data:/var/solr
  #   ports:
  #     - "8983:8983"
    # user: root # run as root to change the permissions of the solr folder
    # # Change permissions of the solr folder, create a default core and start solr as solr user
    # command: bash -c "chown -R 8983:8983 /var/solr && runuser -u solr -- solr start"


volumes:
  db-data:
  solr-data:
  files:
