version: "3.7"
services:
  db:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=omeka-s
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    expose:
      - "3306"
    ports:
      - "3306:3306"

  backend:
    image: biblibre/omeka-s:latest
    environment:
      - MYSQL_HOST=db
      - DB_NAME=collective
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    volumes:
      - ./omeka-modules:/var/www/html/modules
        # - backend-config:/var/www/providence/app/conf
        # - backend-media:/var/www/providence/media/
    depends_on:
      - db
    ports:
      - "8080:80"

volumes:
  db-data: