version: "3.7"
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=omeka-s
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306"

  omeka:
    build: omeka_docker
    #image: giocomai/omeka-s-docker:v3.1.1
    volumes:
      - files:/var/www/html/files
    depends_on:
      - db
      #- solr
    ports:
      - "8001:80"

  # solr:
  #   image: solr:8.8.2
  #   volumes:
  #     - solr_data:/var/solr
  #   ports:
  #     - "8983:8983"
    # user: root # run as root to change the permissions of the solr folder
    # # Change permissions of the solr folder, create a default core and start solr as solr user
    # command: bash -c "chown -R 8983:8983 /var/solr && runuser -u solr -- solr start"

  ocr-service:
    build: ocr_service
    depends_on:
      - omeka

volumes:
  db-data:
  solr-data:
  files:
